Repository Matching42/Matching42-back, pull requests merged in 2021-11, with the labels that each got.

#216 CORS Origin에 테스트용 로컬 도메인 추가
  srcs/app.tsx
Labels: environment

#218 테스트를 위해 CORS Origin 모두 허용
  srcs/app.tsx
Labels: environment

#220 hotfix: 깃 초대 에러 수정
  srcs/controllers/controller.inviteToRepo.tsx
Labels: hotfix

#222 hotfix: 깃 관련 에러 로그 추가
  srcs/controllers/controller.inviteToRepo.tsx
  srcs/lib/lib.createGitRepo.tsx
  srcs/lib/lib.getGitName.tsx
Labels: hotfix

#224 feat: 에러 로그 스택 추적
  srcs/config/winston.tsx
Labels: feature

#226 fix: 스케줄러 시간 서버 시간에 상관 없도록 수정
  srcs/lib/lib.Scheduler.tsx
Labels: hotfix

#228 서브젝트 PDF 링크 업데이트
  srcs/controllers/controller.getSubjectPDF.tsx
Labels: refactoring

#230 env : CI/CD 동작 시점 수정
  .github/workflows/server-cd.yml
Labels: environment
