Repository Matching42/Matching42-back, pull requests merged in 2021-07, with the labels that each got.

#93 feature: git 초대장 발송 API 작성
  srcs/controllers/controller.inviteToRepo.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/inviteToRepo.tsx
Labels: feature

#107 feature : slack msg 발송 api 구현
  srcs/controllers/controller.sendSlackMessage.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
Labels: feature

#108 팀 자동 매칭 시스템 작성
  srcs/lib/index.tsx
  srcs/lib/lib.Matcher.tsx
Labels: feature

#115 [feature] User스키마에 목표기간 속성 추가하기
  srcs/models/model.user.tsx
  srcs/swagger/schema/user.tsx
Labels: feature

#119 팀 스키마에 팀 설명, 팀 태그 추가
  srcs/models/model.team.tsx
  srcs/swagger/schema/team.tsx
Labels: feature

#122 Feat: User스키마에 deadline추가에 따라 api수정
  srcs/controllers/controller.addUser2Waitlist.tsx
  srcs/controllers/controller.removeUser2WaitList.tsx
  srcs/swagger/controller/addUser2Waitlist.tsx
  srcs/swagger/controller/removeUser2WaitList.tsx
Labels: feature

#129 코드 개선 작업
  srcs/controllers/controller.getUser.tsx
Labels: refactoring

#121 getTeam API limit, page 쿼리 값 설정 개선
  srcs/controllers/controller.getTeam.tsx
Labels: refactoring

#134 getTeam API limit, page 쿼리 값 설정 개선
  srcs/controllers/controller.addUser2Waitlist.tsx
  srcs/controllers/controller.getTeam.tsx
  srcs/controllers/controller.getUser.tsx
  srcs/controllers/controller.inviteToRepo.tsx
  srcs/controllers/controller.removeUser2WaitList.tsx
  srcs/controllers/controller.sendSlackMessage.tsx
  srcs/controllers/index.tsx
  srcs/lib/index.tsx
  srcs/lib/lib.Matcher.tsx
  srcs/models/model.team.tsx
  srcs/models/model.user.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/addUser2Waitlist.tsx
  srcs/swagger/controller/inviteToRepo.tsx
  srcs/swagger/controller/removeUser2WaitList.tsx
  srcs/swagger/schema/team.tsx
  srcs/swagger/schema/user.tsx
Labels: refactoring

#133 공통 라이브러리 작성 : 유저 조회 및 에러 처리
  srcs/lib/index.tsx
  srcs/lib/lib.findAllUser.tsx
  srcs/lib/lib.findOneUser.tsx
Labels: refactoring

#124 getTeam API for문 개선
  srcs/controllers/controller.getTeam.tsx
Labels: refactoring

#131 refactor : gitrepo/teamState 리팩토링
  srcs/controllers/controller.createGitRepo.tsx
  srcs/controllers/controller.inviteToRepo.tsx
  srcs/controllers/controller.updateTeamState.tsx
  srcs/controllers/index.tsx
  srcs/models/model.team.tsx
Labels: refactoring

#128 getTeam API 페이지네이션 부분 개선 및 !조건문 구체화
  srcs/controllers/controller.getTeam.tsx
Labels: refactoring

#130 refacor: 특정 Waitlist document 조회 로직 공통 모듈로 빼기
  @types/types.d.tsx
  srcs/controllers/controller.addUser2Waitlist.tsx
  srcs/controllers/controller.removeUser2WaitList.tsx
  srcs/lib/index.tsx
  srcs/lib/lib.allWaitlist.tsx
Labels: refactoring

#137 refactor: 팀 정보 조회 라이브러리 작성
  srcs/lib/index.tsx
  srcs/lib/lib.findAllTeam.tsx
  srcs/lib/lib.findOneTeam.tsx
Labels: refactoring

#135 refactor: 공통 모듈 이름 수정
  srcs/controllers/controller.addUser2Waitlist.tsx
  srcs/controllers/controller.removeUser2WaitList.tsx
  srcs/lib/index.tsx
  srcs/lib/lib.findOneWaitlist.tsx
Labels: refactoring

#139 feat: updateTeamState 를 updateTeam 으로 변경/ updateTeamTag 구현
  srcs/controllers/controller.updateTeam.tsx
  srcs/controllers/controller.updateTeamState.tsx
  srcs/controllers/controller.updateTeamTag.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/updateTeam.tsx
  srcs/swagger/controller/updateTeamTag.tsx
Labels: feature, refactoring

#143 팀 워크스페이스 뷰에 서브젝트 PDF 값 반환하는 API 구현
  srcs/controllers/controller.getSubjectPDF.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/getSubjectPDF.tsx
Labels: feature

#142 refactor: post /waitlist 코드 개선
  srcs/controllers/controller.addUser2Waitlist.tsx
Labels: refactoring

#145 refactor: get /waitlist api 리팩토링
  srcs/controllers/controller.getWaitlist.tsx
Labels: refactoring

#147 refactor: delete /waitlist api 리팩토링
  srcs/controllers/controller.removeUser2WaitList.tsx
Labels: refactoring

#149 refactor: 슬랙 msg 발송 api -> 라이브러리화
  @types/types.d.tsx
  srcs/controllers/controller.sendSlackMessage.tsx
  srcs/controllers/index.tsx
  srcs/lib/index.tsx
  srcs/lib/lib.sendSlackMessage.tsx
  srcs/routes/index.tsx
Labels: refactoring

#159 팀 워크스페이스 뷰에 서브젝트 PDF 값 반환하는 API 구현
  srcs/controllers/controller.getSubjectPDF.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/getSubjectPDF.tsx
Labels: feature
