Repository Matching42/Matching42-back, pull requests merged in 2021-06, with the labels that each got.

#34 DELETE /waitlist 컨트롤러 작성
  srcs/controllers/controller.removeUser2WaitList.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
Labels: feature

#38 Git action test workflow 작성
  .eslintrc.json
  .github/workflow/test.yml
  .gitignore
  __tests__/simple.test.tsx
  jest.config.js
  package-lock.json
  package.json
  srcs/app.tsx
  srcs/index.tsx
  srcs/routes/index.tsx
  tsconfig.json
Labels: environment

#39 merge workflow & testing code
  .eslintrc.json
  .github/workflow/test.yml
  .gitignore
  __tests__/simple.test.tsx
  jest.config.js
  package-lock.json
  package.json
  srcs/app.tsx
  srcs/controllers/controller.addUser2Team.tsx
  srcs/controllers/controller.addUser2Waitlist.tsx
  srcs/controllers/controller.getUser.tsx
  srcs/controllers/controller.removeUser2WaitList.tsx
  srcs/controllers/controller.updateTeamState.tsx
  srcs/controllers/exampleController.tsx
  srcs/controllers/index.tsx
  srcs/index.tsx
  srcs/models/index.tsx
  srcs/models/model.team.tsx
  srcs/models/model.user.tsx
  srcs/models/model.waitlist.tsx
  srcs/routes/index.tsx
  tsconfig.json
Labels: environment

#43 GET team/{teamId} 컨트롤러 작성
  srcs/controllers/controller.getTeam.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
Labels: feature

#54 Development
  .gitignore
  package-lock.json
  package.json
  srcs/app.tsx
  srcs/auth/auth.jwt.tsx
  srcs/auth/auth.lib.tsx
  srcs/auth/auth.tsx
  srcs/auth/controller.login.tsx
  srcs/auth/controller.signup.tsx
  srcs/auth/index.tsx
  srcs/controllers/controller.getTeam.tsx
  srcs/controllers/index.tsx
  srcs/models/model.user.tsx
  srcs/routes/index.tsx
  tsconfig.json
Labels: environment

#56 set Swagger
  package-lock.json
  package.json
  srcs/app.tsx
  srcs/auth/controller.login.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/getUser.tsx
  srcs/swagger/option.tsx
  srcs/swagger/schema/user.tsx
Labels: feature

#57 deployment
  package-lock.json
  package.json
  srcs/routes/index.tsx
  srcs/swagger/controller/getUser.tsx
  srcs/swagger/option.tsx
  srcs/swagger/schema/user.tsx
Labels: feature

#59 feature: swagger에 team schema, updateTeamState controller API 문서 작성
  srcs/swagger/controller/updateTeamState.tsx
  srcs/swagger/schema/team.tsx
Labels: feature

#63 feature : swagger에 담당 API문서작성
  srcs/swagger/controller/addUser2Waitlist.tsx
  srcs/swagger/controller/removeUser2WaitList.tsx
  srcs/swagger/schema/waitlist.tsx
Labels: feature

#68 Development
  srcs/swagger/controller/addUser2Waitlist.tsx
  srcs/swagger/controller/removeUser2WaitList.tsx
  srcs/swagger/controller/updateTeamState.tsx
  srcs/swagger/schema/team.tsx
  srcs/swagger/schema/waitlist.tsx
Labels: feature

#73 GET /team API 반환 값 수정
  srcs/controllers/controller.getTeam.tsx
Labels: refactoring

#78 [fix] 코드의 네이밍을 API 문서, 다이어그램과 통일
  srcs/controllers/controller.creatGitRepo.tsx
  srcs/controllers/controller.updateTeamState.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/updateTeamState.tsx
Labels: hotfix

#80 docs: Swagger로 creatGitRepo API 문서 작성
  srcs/swagger/controller/creatGitRepo.tsx
Labels: planning

#76 fix : API문서, 담당 api 네이밍 통일
  srcs/controllers/controller.addUser2Waitlist.tsx
  srcs/controllers/controller.removeUser2WaitList.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/addUser2Waitlist.tsx
  srcs/swagger/controller/removeUser2WaitList.tsx
Labels: hotfix

#74 Login 기능 DB model 문서와 통일작업 진행
  .eslintrc.json
  @types/types.d.tsx
  srcs/auth/auth.jwt.tsx
  srcs/auth/auth.lib.tsx
  srcs/auth/controller.login.tsx
  srcs/auth/controller.signup.tsx
  srcs/routes/index.tsx
Labels: feature

#82 Development 0.3
  .env.sample
  .eslintrc.json
  @types/types.d.tsx
  srcs/auth/auth.jwt.tsx
  srcs/auth/auth.lib.tsx
  srcs/auth/controller.login.tsx
  srcs/auth/controller.signup.tsx
  srcs/controllers/controller.addUser2Waitlist.tsx
  srcs/controllers/controller.creatGitRepo.tsx
  srcs/controllers/controller.getTeam.tsx
  srcs/controllers/controller.removeUser2WaitList.tsx
  srcs/controllers/controller.updateTeamState.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/addUser2Waitlist.tsx
  srcs/swagger/controller/creatGitRepo.tsx
  srcs/swagger/controller/removeUser2WaitList.tsx
  srcs/swagger/controller/updateTeamState.tsx
Labels: feature

#65 swagger API 문서 작성
  srcs/swagger/controller/addUser2Team.tsx
  srcs/swagger/controller/getUser.tsx
  srcs/swagger/schema/user.tsx
Labels: feature

#85 [fix] 코드 , API 문서, 시퀀스 다이어그램 Naming 통일
  srcs/controllers/controller.addUser2Team.tsx
  srcs/controllers/controller.getUser.tsx
  srcs/models/model.user.tsx
  srcs/routes/index.tsx
Labels: hotfix

#86 fix : swagger의 waitlist모델 오타 수정
  srcs/swagger/schema/waitlist.tsx
Labels: hotfix

#88 feat : GET /waitlist 컨트롤러 작성
  srcs/controllers/controller.getWaitlist.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/getWaitlist.tsx
Labels: feature

#95 Development 0.4
  srcs/controllers/controller.addUser2Team.tsx
  srcs/controllers/controller.getUser.tsx
  srcs/controllers/controller.getWaitlist.tsx
  srcs/controllers/index.tsx
  srcs/models/model.user.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/addUser2Team.tsx
  srcs/swagger/controller/getUser.tsx
  srcs/swagger/controller/getWaitlist.tsx
  srcs/swagger/schema/user.tsx
  srcs/swagger/schema/waitlist.tsx
Labels: feature

#92 feature: 스케줄러 기능 작성
  srcs/lib/index.tsx
  srcs/lib/lib.Scheduler.tsx
Labels: feature

#91 GET /team/{teamID} swagger 문서 작성
  srcs/swagger/controller/getTeam.tsx
Labels: planning

#98 [hotfix] updateTeamState 팀 아이디를 못찾는 현상 버그 해결
  srcs/controllers/controller.updateTeamState.tsx
  srcs/routes/index.tsx
Labels: hotfix

#96 [fix] swagger문서, 시퀀스다이어그램, 코드의 명칭 일치시키기
  srcs/controllers/controller.getTeam.tsx
  srcs/routes/index.tsx
Labels: hotfix

#100 Deploy 0.6
  srcs/controllers/controller.getTeam.tsx
  srcs/controllers/controller.updateTeamState.tsx
  srcs/lib/index.tsx
  srcs/lib/lib.Scheduler.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/getTeam.tsx
Labels: feature

#104 GET team API progress, subject 필터링 추가
  srcs/controllers/controller.getTeam.tsx
  srcs/swagger/controller/getTeam.tsx
Labels: refactoring

#106 Development 0.6
  srcs/controllers/controller.getTeam.tsx
  srcs/swagger/controller/getTeam.tsx
Labels: feature
