Repository Matching42/Matching42-back, pull requests merged in 2021-08, with the labels that each got.

#157 refactor: 깃 저장소 관련 코드 리팩토링
  srcs/controllers/controller.createGitRepo.tsx
  srcs/controllers/controller.inviteToRepo.tsx
Labels: refactoring

#155 addUser2team 컨트롤러 코드에 공통 라이브러리 함수 적용 및 리팩토링 작업
  srcs/controllers/controller.addUser2Team.tsx
Labels: refactoring

#153 유저 조회 API 컨트롤러 분리 작업 및 리팩토링
  srcs/controllers/controller.getAllUser.tsx
  srcs/controllers/controller.getOneUser.tsx
  srcs/controllers/controller.getUser.tsx
  srcs/controllers/index.tsx
  srcs/lib/lib.findAllUser.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/getAllUser.tsx
  srcs/swagger/controller/getOneUser.tsx
  srcs/swagger/controller/getUser.tsx
Labels: refactoring

#168 fix: findAllTeam 리턴 타입 변경
  srcs/lib/lib.findAllTeam.tsx
Labels: hotfix

#164 getTeam API에 공통 모듈 적용및 리펙토링
  srcs/controllers/controller.getTeam.tsx
Labels: refactoring

#171 노션 페이지 발급 라이브러리 함수 구현
  srcs/lib/index.tsx
  srcs/lib/lib.createNotionPage.tsx
Labels: feature

#175 hotfix: 슬랙 msg발송 모듈 에러처리 수정
  srcs/lib/lib.sendSlackMessage.tsx
Labels: hotfix

#176 서버 Logger 구현
  .env.sample
  .gitignore
  package-lock.json
  package.json
  srcs/app.tsx
  srcs/config/winston.tsx
  srcs/index.tsx
Labels: feature

#179 노션 페이지 발급 함수 수정 작업
  srcs/lib/lib.createNotionPage.tsx
Labels: hotfix

#170 refactor: 깃 저장소 생성 API 라이브러리화
  srcs/controllers/controller.createGitRepo.tsx
  srcs/controllers/index.tsx
  srcs/lib/index.tsx
  srcs/lib/lib.createGitRepo.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/creatGitRepo.tsx
Labels: refactoring

#181 fix: invitetorepo 스웨거 문서 오타 수정
  srcs/swagger/controller/inviteToRepo.tsx
Labels: hotfix

#184 데이터 타입 업데이트
  @types/types.d.tsx
  srcs/models/model.team.tsx
Labels: feature

#185 refactor: 슬랙 메시지 발송 라이브러리 인자 수정
  srcs/lib/lib.sendSlackMessage.tsx
Labels: refactoring

#191 유저 스키마에 유저의 과거 팀 리스트 필드를 추가
  @types/types.d.tsx
  srcs/models/model.user.tsx
  srcs/swagger/controller/getAllUser.tsx
  srcs/swagger/controller/getOneUser.tsx
  srcs/swagger/schema/user.tsx
Labels: feature

#190 feat: 사용자가 저장소에 초대되어있는지 확인하는 API 구현
  srcs/controllers/controller.checkGitInvite.tsx
  srcs/controllers/controller.inviteToRepo.tsx
  srcs/controllers/index.tsx
  srcs/lib/lib.getGitName.tsx
  srcs/routes/index.tsx
  srcs/swagger/controller/checkGitInvite.tsx
Labels: feature

#186 fix: team을 end 상태로 변경시 유저의 소속팀 삭제
  srcs/controllers/controller.updateTeam.tsx
Labels: hotfix
