Repository Matching42/Matching42-back, pull requests merged in 2021-05, with the labels that each got.

#6 개발 환경 세팅
  .eslintrc.json
  @types/types.d.tsx
  package.json
  srcs/app.tsx
  srcs/config/index.tsx
  srcs/controllers/index.tsx
  srcs/lib/index.tsx
  srcs/models/index.tsx
  srcs/routes/index.tsx
  tsconfig.json
Labels: environment

#10 Github 설정
  .eslintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue-template.md
  @types/types.d.tsx
  package.json
  srcs/app.tsx
  srcs/config/index.tsx
  srcs/controllers/index.tsx
  srcs/lib/index.tsx
  srcs/models/index.tsx
  srcs/routes/index.tsx
  tsconfig.json
Labels: environment

#11 프로젝트 Git setting
  .eslintrc.json
  .github/.gitmessage
  .prettierrc.json
  package.json
  srcs/app.tsx
Labels: environment

#13 구조 관련 예시 작성 및 임시 DB 추가
  package.json
  srcs/app.tsx
  srcs/config/connectDB.tsx
  srcs/config/index.tsx
  srcs/controllers/exampleController.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
Labels: environment, feature

#22 User DB Model 정의
  srcs/models/model.user.tsx
Labels: feature

#27 GET /user/{userId} 컨트롤러 작성
  srcs/controllers/controller.user.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
Labels: feature

#26 feat: PATCH /team/{teamId} 컨트롤러 작성
  srcs/app.tsx
  srcs/controllers/controller.team.tsx
  srcs/controllers/index.tsx
  srcs/routes/index.tsx
Labels: feature
